### ISSUE TITLE
Album tag not detected in .wav file

### ISSUE THREAD

**Issue by victor-david** [mono/taglib-sharp#103]
When using TagLib to get tags from a .wav file, the Album tag is not detected.
~~~c#
var testFile = TagLib.File.Create(@"F:\temp\01.hihat.wav");
if (String.IsNullOrEmpty(testFile.Tag.Album))
{
    Debug.WriteLine("No album tag");
}
~~~
When I run the above code, "No album tag" is displayed in the output window. However, the file does have an album tag as you can see in the Windows Explorer properties and other programs that show meta data. I've tried this on a directory of .wav files (about 32 files, all with an album assigned) and received the same result for each file. Other properties (title, comment, artist, etc.) are fine.

![capture13](https://user-images.githubusercontent.com/17145322/39088253-2f06cd2c-4574-11e8-9e90-63388533d98b.PNG)

**Comment by victor-david** [comment]
A little more info. I modified my sample code:

~~~c#
var testFile = TagLib.File.Create(@"F:\temp\01.hihat.wav");
if (String.IsNullOrEmpty(testFile.Tag.Album))
{
    Debug.WriteLine("No album tag");
    testFile.Tag.Album = "MY NEW ALBUM";
    testFile.Save();
}
else
{
    Debug.WriteLine($"Album is: {testFile.Tag.Album}");
}
~~~
The **second** time I run the above code, it displays "Album is MY NEW ALBUM". However, Windows Explorer and other programs that show meta data still show the original album. It's like TagLib is writing its Album property to some other place.

**Comment by Starwer** [comment]
I was able to reproduce this issue with any random wav file tagged with Foobar2000. 
The Album tag is not put in the Riff-`LIST` then, but instead an ID3 section is created at the end of the file. This `id3` tag at the end is beautifully ignored by the Riff-parser in `TagLib.Riff.File.Read`.

I don't know so much about audio tags and how this Riff part is supposed to work, so help from more experience users in that field here would be appreciated (doc or contribution welcome).

**Comment by bnickel** [comment]
When I wrote this code, there was no standard for storing ID3 information in RIFF files and I don't think anyone else was doing it.  Really, there still isn't a standard but some more common taggers are writing it and Windows is reading it.

I store my code in a section called `ID32` but it looks like [everyone else is using `ID3<space>` and `id3<space>`](https://github.com/Borewit/music-metadata/wiki/RIFF-WAVE).

I think the appropriate solution would be to expand reading at:

https://github.com/mono/taglib-sharp/blob/master/src/TagLib/Riff/File.cs#L586

to be:

```c#
				case "ID3 ":
				case "id3 ":
				case "ID32":
					if (read_tags && id32_tag == null)
						id32_tag = new Id3v2.Tag (this,
							position + 8);
					
					tag_found = true;
					break;
```

And change:

https://github.com/mono/taglib-sharp/blob/master/src/TagLib/Riff/File.cs#L251

to:

```c#
						data.Add ("id3 ");
```

**Comment by Starwer** [comment]
Wow! That's more help than I was expecting. That's looks like a complete solution ! Thanks a lot @bnickel ! I'll definitly try this out !

**Comment by victor-david** [comment]
Thanks @bnickel - I looked into the code myself, but don't know enough about how tags are stored to really learn anything. Your investigation is a big help.

**Comment by Starwer** [comment]
Thanks again  @bnickel: Ive implemented you proposal... and this indeed solves the issue !

**Comment by decriptor** [comment]
Fixed here: https://github.com/mono/taglib-sharp/pull/108
