### ISSUE TITLE
Multiple genre's is not being handled correctly

### ISSUE THREAD

**Issue by DocCaliban** [mono/taglib-sharp#111]
I've tested this with several 3rd party tools: mp3tag, MP4 Tag Library, etc...

It appears that when the library is saving multi genre's it save them as a semicolon delimited string.
This string is being read as a single string in other applications, rather than a list of Genre's.

Additionally when multiple genre tags are added to a file by other applications, the library doesn't read them and return an empty list.

**Comment by Starwer** [comment]
I could reproduce the problem easily with foobar2000... embarrassing bug indeed...

**Comment by Starwer** [comment]
> Additionally when multiple genre tags are added to a file by other applications, the library doesn't read them and return an empty list.

This is now fixed in #113. Problem was that the semicolon as list-separator in ID3 v2.3 (commonly used) was specific to the Genres (`TCON`) tag and not supported by TagLib#.
As lists in ID3 v2.4 are well-defined, there is no problem like this in ID3 v2.4.

> It appears that when the library is saving multi genre's it save them as a semicolon delimited string.
 This string is being read as a single string in other applications, rather than a list of Genre's.

I didn't try that yet. I guess I'll have to fix that as well.

**Comment by Starwer** [comment]
> It appears that when the library is saving multi genre's it save them as a semicolon delimited string.
 This string is being read as a single string in other applications, rather than a list of Genre's.

This should now be fixed as well.

**Comment by Starwer** [comment]
Fix is now available (Merged: #113).
@DocCaliban: Could you please verify that the problem is solved and close the issue ?

**Comment by DocCaliban** [comment]
Ran a few quick tests, this is partially functional; I think intentionally.

For Mp3's it works just fine.  For mp4 & matroska video it doesn't work, however I'm not sure you have added support for that yet, or if you even plan to.   

Regardless this solves the issue I filed, so if anyone else wants to add a new request for video, then by all means please do.
