### ISSUE TITLE
Wrong Duration for Mpeg?

### ISSUE THREAD

**Issue by mail4andrey** [mono/taglib-sharp#119]
https://github.com/mono/taglib-sharp/blob/fe2cc47f0cf564a399d3ba18d6dfb0d387445d74/src/TagLib/Mpeg/AudioHeader.cs#L477

Why "+1" in  `int frames = (int) (stream_length / AudioFrameLength + 1);` may be need `Math.Ceiling(stream_length / AudioFrameLength)`

and below why +0.5 seconds in 
`duration = TimeSpan.FromSeconds (
						(double) (AudioFrameLength *
						frames) / (double)
						(AudioBitrate * 125) + 0.5);`

**Comment by mail4andrey** [comment]
Thanks for fast answer.
We just looked for some .net instrument for get duration of mp3. Our files don't have tag headers (so sad). And taglib returned other duration than naudio (more on half a seconds).

Yes, your answer more right. I broke my brains to understand about these half a second.)

**Comment by Starwer** [comment]
I've done a fix locally. I intend to issue a PR soon to solve this issue (and a few others that I could find).

**Comment by mail4andrey** [comment]
Great! Thanks!
