### ISSUE TITLE
Album title not saving?

### ISSUE THREAD

**Issue by DavidOrazine** [mono/taglib-sharp#122]
Hello everyone,

I have a project that uses this library. Everything is working great except the album name is not being tagged. I can see the value is there at run time, when I save the tag info, open it up with a tag reading software, these is everything there except the album name. I am new to tagging, am I doing anything wrong?

I have tried adding these lines to the program:

            TagLib.Id3v2.Tag.DefaultVersion = 3
            TagLib.Id3v2.Tag.ForceDefaultVersion = True
            TagLib.Id3v2.Tag.ForceDefaultEncoding 

These have not yielded any luck.

Thanks in advance!

**Comment by DavidOrazine** [comment]
Dim file As TagLib.File = TagLib.File.Create(Form1.CleanFileName(tagTrack.Path))
file.Tag.Title = tagTrack.Title
TagLib.Id3v2.Tag.DefaultVersion = 3
TagLib.Id3v2.Tag.ForceDefaultVersion = True
TagLib.Id3v2.Tag.ForceDefaultEncoding = True
file.Tag.Performers = tagTrack.Artist.ToArray
file.Tag.AlbumSort = tagTrack.Title.Replace("Side A", "").Replace("Side B", "")
file.Tag.Album = tagTrack.Title.Replace("Side A", "").Replace("Side B", "")
file.Tag.Year = tagTrack.Year
file.Tag.Track = tagTrack.Track
file.Tag.Genres = tagTrack.Genre.ToArray
file.Tag.AlbumArtists = tagTrack.AlbumArtist.ToArray
file.Tag.Composers = tagTrack.Composer.ToArray
file.Save()

**Comment by PeterCodar** [comment]
You wrote "...these is everything there except the album name".
Are you really sure, that the AlbumSort is filled correctly, but not the Album for the same track?
Would the Album be filled in a test case , if you don't use .Replace?

**Comment by DavidOrazine** [comment]
The AlbumSort line was me playing around trying to get the Album name to work. That was not originally supposed to be tagged so I have not payed attention to that one.

Removing the .Replace as a test still did not fix the Album name tag from not working.

Thanks for the quick response!

**Comment by flagoworld** [comment]
Album doesn't save for me either...

**Comment by Starwer** [comment]
The way the tags are written is pretty format-dependent. Could you please indicate what extension the file you try to save has, or if possible provide the file itself (beware of copyrights) ?

**Comment by flagoworld** [comment]
Riff / Wav

I could try to repo with a safe file and share it if i can

**Comment by DavidOrazine** [comment]
The problem was with the file type. After I converted it to a FLAC file from a WAV file it worked perfectly. Thanks for your help, everyone!

**Comment by flagoworld** [comment]
Please reopen. The but with wav still exists.
