### ISSUE TITLE
Just a simple question regarding MyFile.Tag.Pictures

### ISSUE THREAD

**Issue by EnanoFurtivo** [mono/taglib-sharp#131]
### Hi! I have been using this library in my code for a while and never really noticed this little detail before.
**Thing is i have set up a program that copys a cetrain mp3 file from one directory into anotherone:**
     ` System.IO.File.Copy(songn.Mp3Path, mp3CopyPath, true);`

**I then use this new mp3 to edit with the library to apply some tags:**
```
      var file = TagLib.File.Create(mp3CopyPath);
      file.Tag.Title = songn.Title;
      file.Tag.AlbumArtists = songn.Artist.Split(new char[] { ';' });
      file.Tag.Album = songn.Collection;
      file.Tag.Comment = songn.Hash;
```

**_ACTUALL ISSUE:_** 
**Then comes the issue, when i try to apply a cover to it:**
```
      TagLib.Picture pic = new TagLib.Picture();
      pic.Type = TagLib.PictureType.FrontCover;
      pic.Description = "Cover";
      pic.MimeType = System.Net.Mime.MediaTypeNames.Image.Jpeg;

      try
      {
            pic.Data = TagLib.ByteVector.FromPath(ImagePath);
      }
      catch (Exception)
      {
            if (System.IO.File.Exists(imgPath))
            {
                  pic.Data = TagLib.ByteVector.FromPath(imgPath);
            }
            else
            {
                  Resources.Defaultsongthumbnail.Save(imgPath, System.Drawing.Imaging.ImageFormat.Png);
                  pic.Data = TagLib.ByteVector.FromPath(imgPath);
            }
      }
```

Now the thing is ImagePath is the path to the image on the left wich is the one supposed to be used as a cover but when i open the mp3 i get the image on the right wich is totally a different one, is there any step im missing or something im doing that i shouldnt? Maybe its autodetected by amozon or some music app and being auto changed?
*also the original mp3 does not contain a cover when i open it so i dont really know where its taking the picture from if not from ImagePath
*mind you this is inside a foreach statement BUT im debugging it with only 1 object in my list so undiscarded objects shouldnt really be a problem.
*Also it does not enter the catch so it will always be pic.Data = TagLib.ByteVector.FromPath(ImagePath);

![screenshot_400](https://user-images.githubusercontent.com/31115763/47529839-54cd7f80-d87f-11e8-9b6d-0a0c0a934070.png)

**Comment by EnanoFurtivo** [comment]
Maybe it has to do with the fact that the image is in jpg format and this line here specifies Jpeg idk for real
`pic.MimeType = System.Net.Mime.MediaTypeNames.Image.Jpeg;`

**Comment by Starwer** [comment]
The first thing to understand is: where does this other unexpected image come from... Looks tom me like VLC is making it up by using a cache or by automatically downloading it... Maybe you can challenge it by just putting a dummy file-name to your newly created mp3, and also dummy metadata title and album.
Also try to open this mp3 with another software to see if this is consistent. Or simply: was this image present in the source mp3 file ?
I also miss the snipet where you actually assign the `TagLib.Picture` instance to the `TagLib.File` (mp3) object.

**Comment by Starwer** [comment]
I'm now pretty curious where this magic image comes from... :)

The `Comment` Tag is a standard feature for many formats, but rarely used indeed.  It is really meant to store the user comments, whatever it may be. So it is safe to use it for storing whatever you like there.
Still, if you only deal with MP3, you may want to create your own custom tag. I explained how to do this in: https://github.com/Starwer/taglib-sharp/tree/miscfix_doc#readwrite-custom-tags-from-a-specific-format. The drawback of this is that it will only work on on file-type (MP3), but that may be acceptable in your usecase.

Another trick: the code you provided seems pretty OK, but you have simpler ways to do that:
```C#
      TagLib.Picture pic; 
      try
      {
            pic = new TagLib.Picture(ImagePath);
      }
      catch (Exception)
      {
            if (System.IO.File.Exists(imgPath))
            {
                  pic = new TagLib.Picture(imgPath);
            }
            else
            {
                  Resources.Defaultsongthumbnail.Save(imgPath, System.Drawing.Imaging.ImageFormat.Png);
                  pic= new TagLib.Picture(imgPath);
            }
      }
     pic.Type = TagLib.PictureType.FrontCover;
     pic.Description = "Cover";
     file.Tag.Pictures = new TagLib.IPicture[] { pic };
     file.Save();
```

The Mimetype is picked automatically from the file-extension.
BTW, I think the `Description` field is just ignored (not saved) in a MP3, because it is not supported by the ID3v2 format.

**Comment by EnanoFurtivo** [comment]
Okay this is suprisingly interesting, **when opening the file in Windows Media Player it shows the correct cover**. I'm even more curious now that i know **VLC is using a cover created from thin air**, i would like to investigate where that comes from in the near-future. And thanks for the tip regarding the comment tag. I guess this issue could be closed now, unless there is a way to override this: i guess "internet" cover thing wich would be cool, maybe theres a tag for that im not an mp3 expert tbh. Also i just realized WMP resizes the cover to make it squared which looks horrible, what a bad media player lol.

![screenshot_401](https://user-images.githubusercontent.com/31115763/47576728-96ac0380-d91b-11e8-8de1-4e278bfabfb8.png)

**Comment by Starwer** [comment]
Welcome ! You're the only one who can close this issue, so please do it if you think your problem is solved.

**Comment by EnanoFurtivo** [comment]
Sorry i thought you were the owner of the repo my bad. I'll close the issue here. If find out what VLC is doing ill post it as a add on to the closed issue. Thank you for the support :D
