### ISSUE TITLE
Unicode Filenames

### ISSUE THREAD

**Issue by Wizard-K** [mono/taglib-sharp#140]
Taglib cannot open a file (Windows) which has unicode characters in the filename.  Example: Jean-Michel Jarre - Téo & Téa Promo - 10 - Gossip.mp3 (note the accented e's)

**Comment by DoctorWiz** [comment]
Nevermind.  Filename is getting screwed up somehow before passing it to Taglib.

**Comment by decriptor** [comment]
ok, I'm going to close this. If it is a real problem though please feel free to reopen the issue
