### ISSUE TITLE
How do I read Audio file and turn it to float[] ?

### ISSUE THREAD

**Issue by kwangsing3** [mono/taglib-sharp#150]
First, thank you guys for this powerful lib, 
but after some researched, I still can't fix my problem.
I'm using it to my UnityEngine game to load Audio file( Wav,Mp3, Flac....) at runtime, and most the thing I got was great, I can print some properties, so I do load the file successfully, But Unity Audio API needs float[] to set new audio file, just like 
AudioClip.Setdata(float[] data, int offsetsamples);

I'm sure probably I do something wrong, but I can't find the better way after reading Source Code,
and sorry I've to ask this here, cause I can't find other question like this using in Unity.
```C#
   IEnumerator loadMusic(string input_path)
    {
         File _newfile = File.Create(input_path);
        string _newfileTitle = _newfile.Tag.Title;

        TimeSpan duration = _newfile.Properties.Duration;
        int _lengthSeconds = duration.Minutes * 60 + duration.Seconds; 
          _newfile.Tag.Title = _newfileTitle;
          _newfile.Save();

        byte[] _byt =_newfile.ReadBlock((int)_newfile .Length).Data;  // I got Null here, and I have no idea  
                                                                                              //  I always got AccessMode.closed.

        float[] _flo = new float[_byt.Length];
        for (int i = 0; i < _byt.Length; i++)
        {
            _flo[i]=  Convert.ToSingle(_byt[i]);
        }   
        _audioSource.clip.SetData( _flo, 0);
        _audioSource.Play();
        yield return null;
    }
```

**Comment by Starwer** [comment]
There are two problems in using `ReadBlock` this way:

-  You don't know at what file position it starts to read the file content. This depend on the way TagLib reads the file internally;
- After the call to `_newfile.Save()` Your file stream is considered to be `closed`, meaning that you can't do anything anymore with it. 

The solution: try to add this line before you use the ReadBlock:  `_newfile.Mode = AccessMode.Read;`. This will re-open the file stream for reading and reset the Seek position to read the file to its beginning.

**Comment by kwangsing3** [comment]
> There are two problems in using `ReadBlock` this way:
> 
> * You don't know at what file position it starts to read the file content. This depend on the way TagLib reads the file internally;
> * After the call to `_newfile.Save()` Your file stream is considered to be `closed`, meaning that you can't do anything anymore with it.
> 
> The solution: try to add this line before you use the ReadBlock: `_newfile.Mode = AccessMode.Read;`. This will re-open the file stream for reading and reset the Seek position to read the file to its beginning.

Thank you ! you're right, I successfully got it.
I appreciate that you help me to fix it !

**Comment by decriptor** [comment]
I'm assuming we are good and can close this then?
