### ISSUE TITLE
Linking fails on Xamarin.iOS due to missing reference "ICSharpCode.SharpZipLib"

### ISSUE THREAD

**Issue by velocitysystems** [mono/taglib-sharp#152]
### Description
Linking fails on a Xamarin.iOS project due to a missing reference to "ICSharpCode.SharpZipLib".

### Steps to Reproduce
1. Create a Xamarin.iOS project 
2. Add Taglib nuget to the project
3. Try to build and deploy to the iOS simulator (or device)

**Workaround: Add SharpZipLib nuget package to the project and rebuild.**
_This nuget package should be added as a dependency in the .nuspec definition for taglib on iOS._

### Expected Behavior
Linking should be successful.

### Actual Behavior
Linking fails due to a missing reference assembly.

### Basic Information

- Version with issue: Taglib 2.1.0

**Comment by decriptor** [comment]
As far I know we aren't using SharpZipLib in TaglibSharp. Is there something else that might be trying to bring in SharpZipLib?

Could you try this package instead and see if that is still an issue: https://www.nuget.org/packages/TagLibSharp/2.2.0-beta
