### ISSUE TITLE
Replace GTK# dependency in Unit Tests with ImageSharp (maybe)

### ISSUE THREAD

**Issue by decriptor** [mono/taglib-sharp#155]
We only use GTK# for a very small part of our unit tests. It'd be nice to get rid of that dependency. Is ImageSharp an option? https://github.com/SixLabors/ImageSharp

**Comment by Starwer** [comment]
We would then replace the GTK# dependency by another one then, isn't it ?
What is the the advantage of using ImageSharp over GTK# ?

**Comment by decriptor** [comment]
In my current PR #215 I've switched out to ImageSharp instead of gtk#. The negative to this is that TIFF isn't support yet (there is a PR). The upside to using ImageSharp is there are no additional dependencies. For example, we don't depend on gtk+ being installed. Also, it seems crazy to bring in an entire UI toolkit and platform just to validate the md5sum on some images :D
