### ISSUE TITLE
How to write custom tag

### ISSUE THREAD

**Issue by orobert91** [mono/taglib-sharp#160]
How do we write custom tags with this library? I have tried TextInformationFrame and UserTextInformationFrame but it has 2 problems:

1. It doesn't show in Windows Explorer in the properties of the file.
2. Windows Explorer messes up the data stored in TextInformationFrame and UserTextInformationFrame  when it overwrites the properties.

Is it even possible to do this in taglib-sharp?

**Comment by Starwer** [comment]
What do you expect `TextInformationFrame` and `UserTextInformationFrame` to be mapped to in Windows Explorer ?

- If you're looking for the TagLib# equivalent to the Windows Explorer "Comment", you should better use the `Tag.Comment` property. This doesn't map to `TextInformationFrame` but a `CommentsFrame` (COMM) instead.
- If you really need to access the `UserTextInformationFrame` (TXXX), you shall use the `Tag.Description` property in TagLib#. However, to my knowledge, this is not a visible attribute in Windows Explorer. 
- If you really need to access the specific Frames of an ID3 file in TagLib# you should check this example: https://github.com/mono/taglib-sharp#readwrite-custom-tags-from-a-specific-format. However, you'll have to tune the snippet to retrieve an ID3 tag.

**Comment by orobert91** [comment]
I do not wish the field to be mapped to an existing tag, but rather create a new tag that Windows Explorer will be able to show in the "Details" tab of the file properties dialog, like this:

![image](https://user-images.githubusercontent.com/6403705/57661807-63307e00-75ba-11e9-8669-ad038f47dab3.png)

These two tags are created by Traktor Pro 3 after analyzing an mp3 file. I have looked into the frames using TagLib and it seems to be TextInformationFrame identified as TKEY, but the description "Initial Key" is not in any field and I can't find a way to create a TextInformationFrame in TagLib that puts up a readable description like above.
