### ISSUE TITLE
TRACK frame is typed UInt but is defined as string in the id3 standard.

### ISSUE THREAD

**Issue by dvshmkr** [mono/taglib-sharp#161]
This value is not for doing math. Existing data my have other non-numeric values "/". It's defined in the standard as a string.

**Comment by Starwer** [comment]
So far, allowing zero-leading in value was the only issue I could think of with presenting TRACK as `Uint` (example to sort alphabetically on 01, 02, 03...). However, this has been discussed and solved in issue #64.

@dvshmkr : Could you please give an example of value in `TRACK` that would not be an `Uint` and would make sense anyway ? Does your "/"suggest that you want to allow multiple tracks to be mapped on one file ?

**Comment by dvshmkr** [comment]
Sebastien,
Thanks for responding so quickly to my issue. It's great to know tablib is
under active development.
First, thanks to you and the other taglib developers for your work; I was
able to port my project to C# very quickly with it.

Regarding TRACK being a Uint: For me the issue came up because some of the
files I'm processing have a letter prefixing the numeric track to represent
the disc on multi disc albums. (A01, B01, etc). The library I previously
used allowed this and It's worked out as a good solution. Although TRACK is
typically a number, it's not a number for doing math and so there is no
value in limiting it to Uint. The same would be true for a zip-code. I
think the strongest argument is that the id3 standard defines the frame as
a numeric string but still a string. It's even listed under the text frames
heading. The standard has a specific example of including a "/" in the
frame to identify TRACK / TOTAL-TRACKS. So ultimately, any tags written by
a library that follows the standard and happen to contain non-numeric
values will not be read correctly by taglib.

Anyway, thanks for hearing my point of view. I like your library and wish
you guys the best of luck with it.

Dave Shoemaker

ps - I'm making the assumption that you are trying to follow the id3
standard published at id3.org, if that's not the case then please accept my
apologies and disregard.

**Comment by Starwer** [comment]
Hi Dave,

Ok, now I understand your confusion. 

First of all, yes, your assumption is right: TagLib aims at following the standards like ID3 as close as possible.

Now the `Tag` abstract doesn't present each specific standard flavour like the TRCK frame for ID3. This class abstracts the specificities of each tag-format. This is for a good reason: reusability. You can handle ID3 files the same way as ogg or wav files, and you don't care how the standard is built.

For your  example, the TAgLib# way to do it is:
```C#
var tfile = TagLib.File.Create(@"C:\My audio.mp3");
uint track = tfile.Tag.Track;
uint trackCount= tfile.Tag.TrackCount;
uint disc= tfile.Tag.Disc;
uint discCount= tfile.Tag.DiscCount;
Console.WriteLine("Track: {0} / {1}, disc: {2} / {3}", track , trackCount, disc, discCount);

// change track in the file
tfile.Tag.Track = 8;
tfile.Tag.TrackCount = 15;
tfile.Save();
```

Doing this, TagLib# takes care of parsing/forming the right `TRCK` frame under the hood (using string: `08/15`). 

Now the disc coding doesn't accept the letters. But the ID3 standard doesn't recommend it either. It recommends instead the use of TPOS frame. Again, with TagLib# you don't need to care about this. using the `Tab.Track` and `Tag.TrackCount` properties it will map it properly to the TPOS frame under the hood.

Now if you really want to address the ID3 frames strings directly, you can do it with TagLib#: 
```C#
var tfile = TagLib.File.Create(@"C:\My song.mp3");
var custom = (TagLib.Id3v2.Tag) tfile.GetTag(TagLib.TagTypes.Id3v2);
```
You can then use the public methods of `TagLib.Id3v2.Tag` to retrieve or change the frames in the ID3 file. But this code will work with ID3 files only. IMHO, to use as a last resort.
