### ISSUE TITLE
Id3v2: Setting TrackCount after Track removes leading 0

### ISSUE THREAD

**Issue by EatonZ** [mono/taglib-sharp#166]
"_Most tagging formats store this as a string. To help sorting, a two-digit zero-filled value is used in the resulting tag._" - [Track documentation](https://github.com/mono/taglib-sharp/blob/83f5f2c36655a872b5cee46cf0fff1e020d05558/src/TaglibSharp/Tag.cs#L568)

I discovered when working with Id3v2 that if you set the value of `Track`, and then `TrackCount`, it removes the leading 0 from `Track` when it is written to the file. However, if you set `TrackCount`, and then `Track`, the leading 0 remains.

The solution is to simply add the "00" `format` argument [here](https://github.com/mono/taglib-sharp/blob/83f5f2c36655a872b5cee46cf0fff1e020d05558/src/TaglibSharp/Id3v2/Tag.cs#L1708).

Tried doing a pull request, but the diff ended up being ridiculous because of line ending issues. I'll leave it to someone else.😉

**This issue may affect other tag types as well.** You may want to double-check the others.

**Comment by EatonZ** [comment]
Any thoughts on this yet?

**Comment by decriptor** [comment]
@EatonZ I'll add this and the other issue to my todo list. If you still have the PR with the fix and unit test(s) and can submit it that'd be great even if it has a bunch of line ending problems. I can try and pull in the change without pulling in the line ending changes.

**Comment by EatonZ** [comment]
@decriptor Looks like someone fixed the line endings, so there were no issues with my PR today.🙂
