### ISSUE TITLE
pkg-config support was removed

### ISSUE THREAD

**Issue by Adsun701** [mono/taglib-sharp#171]
#169 removed support for pkg-config when transitioning from autotools to msbuild. Some applications require pkg-config when searching for taglib-sharp as a required dependency. Is there a reason to why pkg-config support was removed?

**Comment by decriptor** [comment]
I removed most everything outside of a simple `msbuild`. Can you help me understand the value of pkg-config? I'm opposed to adding autotools back, but am open to pkg-config.

I don't believe taglib-sharp should be in the gac and assumed that if it wasn't in the gac that the pkg-config wouldn't serve as much purpose.

@directhex Do you have any suggestions or feedback on this?

**Comment by directhex** [comment]
taglib-sharp 2.1.0.0 installs to the GAC in distributions as-is.

`pkg-config` is historically nice for libs, since it gives you things like the `-pkg:foo` flag to mcs, and easy minimum version checking in autotools projects which consume it.

Removing the pcfile will break the build of existing GAC-assumed consumers like, say, [tangerine](https://github.com/snorp/tangerine/blob/master/configure.ac#L27) or [banshee](https://github.com/GNOME/banshee/blob/master/build/m4/banshee/taglib.m4#L3).

Question is whether you want to keep supporting that scenario ad infinitum, since _new_ projects are much more likely to consume via NuGet, in a post-GAC world.

**Comment by Adsun701** [comment]
I think pkg-config support should be retained even if autotools is removed. An autotools configure script is not necessary to install a .pc file.

For example, the taglib-sharp [PKGBUILD ](https://aur.archlinux.org/packages/taglib-sharp) in the Arch User Repository now manually installs a [.pc file](https://aur.archlinux.org/cgit/aur.git/tree/taglib-sharp.pc?h=taglib-sharp) to avoid breakage of other packages that depend on it (such as basenji).

**Comment by decriptor** [comment]
@directhex @Adsun701 I'm not sure I'm very interested in supporting a non-nuget future. I'd probably recommend a submodule and include the TaglibSharp.csproj file in your solution or just pull in the nuget.

Having said that though, @Adsun701 if you were interested in creating a PR to add the `.pc` skeleton file I'd be ok including it in the repo. Without the `configure` stuff it'll probably have to modified a bit per distro though.

https://github.com/mono/taglib-sharp/blob/21d46dfe616a2293c549f94ba4c2d6ba53bea131/taglib-sharp.pc.in

**Comment by decriptor** [comment]
Are things like tangerine or banshee or others still maintained and distributed still? It looks like the era of c# desktop development on Linux is mostly or completely dead?

**Comment by Adsun701** [comment]
@decriptor Actually, C# desktop development is very much alive on Linux. I could not say the same for Visual Basic .NET however, at least not at this moment.

**Comment by decriptor** [comment]
@Adsun701 That is good to hear. Do you have some examples of c# desktop development on Linux?

**Comment by Adsun701** [comment]
- [IPBan](https://github.com/DigitalRuby/IPBan), a C# application used on Windows and Linux for banning IP addresses
- [BloomDesktop](https://github.com/BloomBooks/BloomDesktop), creates simple books for translation into multiple languages
- [Eto](https://github.com/picoe/Eto), a GUI framework

It can be seen that new cross-platform projects are being created in C# on Github every week.
