### ISSUE TITLE
I cant add this library to my Project. 

### ISSUE THREAD

**Issue by GeAd23** [mono/taglib-sharp#176]
I cant find any dll for 2.2.0.0. So how can i add taglib-sharp to my project or where can i find the taglib-sharp.dll ?

**Comment by GeAd23** [comment]
But there is no Version 2.2.0.0 !

**Comment by codenotworking** [comment]
@GeAd23 Download and install [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/?q=build+tools).  Then run `msbuild.exe /restore TaglibSharp.sln` to build the DLL file.  You'll get both .NET Framework 2.0 and 4.5 versions.
