### ISSUE TITLE
How do I do TagLib.File.Create in UWP?

### ISSUE THREAD

**Issue by SeakyLuo** [mono/taglib-sharp#177]
I cannot do the creation in UWP, as I get `System.UnauthorizedAccessException:“Access to the path is denied.”` using either `TagLib.File.Create(new TagLib.File.LocalFileAbstraction(CurrentMusic.Path), TagLib.ReadStyle.Average);` or `TagLib.File.Create(CurrentMusic.Path, TagLib.ReadStyle.Average);`.

I previously used Id3 library and I was able to access the music file using stream like the following but I cannot do that directly using path. And I have an issue writing tag using that library so I decide to switch to taglib.

            var file = await StorageFile.GetFileFromPathAsync(CurrentMusic.Path);
            using (var stream = await file.OpenAsync(FileAccessMode.ReadWrite))
            {
                using (var mp3 = new Mp3(stream.AsStream(), Mp3Permissions.ReadWrite))
                {
                    var tag = mp3.GetTag(Id3TagFamily.Version2X);
                    tag.Lyrics[0] = Lyrics;
                    mp3.WriteTag(tag, tag.Version, WriteConflictAction.Replace);
                }
            }

**Comment by MrCSharp22** [comment]
```System.UnauthorizedAccessException``` is thrown when your UWP app is accessing a file outside of the app data folder.

How are you getting the path of the file you want to open? You should be using the file picker which will grant your application permissions to access the selected file.

**Comment by SeakyLuo** [comment]
Yes I am accessing a local drive music file. I am implementing a UWP music player that manages local music files. How can I get a local file using your library?

**Comment by MrCSharp22** [comment]
Ok, so the thing about UWP is that Apps can't just get access to a file using only a path. From your comment I see that you need to give your app the "Music Library" capability under the "Capabilities" section of the app manifest in Visual Studio.

This capability will allow your app to have full access to the user files in their Music folder. However, if there are other music files outside of the music folder, then your app needs to use the ```FileOpenPicker```. The reason here is that once a user selects a file through that dialog, Windows will grant your app access rights to that file until your app is closed.

**Comment by SeakyLuo** [comment]
I understand this issue in the UWP programming. I am just wondering, if I use FileOpenPicker and get a StorageFile, then how should I use your library to get the tag of that music file?

**Comment by MrCSharp22** [comment]
You don't have to copy it to the app folder. If you use the FileOpenPicker then just use the ```OpenAsync``` method on the ```StorageFile``` object you get from it. Then proceed as per the code you've showed above without the call to ```GetFileFromPathAsync```

**Comment by SeakyLuo** [comment]
Yes but how to use your library to get the tag with the ```StorageFile```?

**Comment by SeakyLuo** [comment]
Hello, any suggestions? I didn't find a similar call to the code I showed above.

**Comment by MrCSharp22** [comment]
Hey buddy, I'm sorry I didn't reply earlier.
Here's a snippet of the code I've used before:

Start by creating this class. It is a simple wrapper for the file abstractions interface offered by the library:

```
public class UwpStorageFileAbstraction : TagLib.File.IFileAbstraction
    {
        private readonly StorageFile file;

        public string Name => file.Name;

        public Stream ReadStream
        {
            get
            {
#pragma warning disable DF0023 // Disposing of this is handled by the TagLibSharp lib by calling the CloseStream method defined here
                return file.OpenStreamForReadAsync().GetAwaiter().GetResult();
#pragma warning restore DF0023 // Disposing of this is handled by the TagLibSharp lib by calling the CloseStream method defined here
            }
        }

        public Stream WriteStream
        {
            get
            {

#pragma warning disable DF0023 // Disposing of this is handled by the TagLibSharp lib by calling the CloseStream method defined here
                return file.OpenStreamForWriteAsync().GetAwaiter().GetResult();
#pragma warning restore DF0023 // Disposing of this is handled by the TagLibSharp lib by calling the CloseStream method defined here
            }
        }


        public UwpStorageFileAbstraction(StorageFile file)
        {
            if (file == null)
                throw new ArgumentNullException(nameof(file));

            this.file = file;
        }


        public void CloseStream(Stream stream)
        {
            stream?.Dispose();
        }
    }
```

Then, use this method to read tags from an MP3 file:

```
public void ReadTags(File.IFileAbstraction fileAbstraction)
        {
            using (var tagFile = File.Create(fileAbstraction, ReadStyle.Average))
            {
                //read the raw tags
                var id3v2Tags = tagFile.GetTag(TagTypes.ID3V2, true);

                // do stuff with the tags 
            }
        }
```

Hope this helps mate.

**Comment by SeakyLuo** [comment]
Thank you!!! Now it is working like a charm. I really suggest you guys to put this code sample onto the README or somewhere!

**Comment by MrCSharp22** [comment]
Hi @SeakyLuo 
I'll try to submit a pull request soon with this.
For now, feel free to close the ticket as resolved.

Good luck!
