### ISSUE TITLE
Update README.md to include nuget reference

### ISSUE THREAD

**Issue by jamesjohnmcguire** [mono/taglib-sharp#192]
It might be slightly helpful to include an explicit reference to the nuget package: https://www.nuget.org/packages/TagLibSharp in the readme.

If you just do a search for 'nuget taglib', this package actually comes about fourth.  While the top one, seems to be variation (just taglib) that is still on version 2.1.0.

**Comment by decriptor** [comment]
@jamesjohnmcguire that is a great point! Would you be willing to submit a PR for this?

If not, I'm happy to do it.

**Comment by jamesjohnmcguire** [comment]
@decriptor Ok. I'll setup a PR for this.
