### ISSUE TITLE
GEOB (General Encapsulated Object)

### ISSUE THREAD

**Issue by wim07101993** [mono/taglib-sharp#202]
Is there a way to get the GEOB from the tags?

**Comment by Starwer** [comment]
Hi @wim07101993 , 

Sure! You can get these using `Tag.Pictures`. This returns Pictures (`APIC`) and non-picture objects (`GEOB`). See #199.

**Comment by wim07101993** [comment]
Ok thanks, i will have a look at that. The reason I ask is because some programs (eg: MixedInKey) store cue points in that data. Since you are able to parse the picture inside the GEOB, is there also a property to get those values?

**Comment by Starwer** [comment]
For TagLib#, a `IPicture` just represents raw binary data that you can access using property `IPicture.Data`. It doesn't interpret what's there... it can only assess whether this has a known picture header, and still there this is not exhaustive, and that why it is useful to set the picture type `IPicture.Type` explicitly to register what this represents.
So I don't know in what format the cue is stored in those programs and how to parse these.

**Comment by wim07101993** [comment]
ok thanks
