### ISSUE TITLE
Merge PR #190 & release new NuGet package to add support for .NET Core 3.1

### ISSUE THREAD

**Issue by willkara** [mono/taglib-sharp#214]
Starting on another project using .NET Core and would love to use taglib-sharp.

Nuget still complains about it "not being targeted for .NET Core 3.1"

Looks like PR #190 is open and would add support.

**Comment by decriptor** [comment]
I'm going to try to knock this out over the weekend. 🤞

**Comment by willkara** [comment]
You da man! I’ll be available to test once available on NuGet 😊

**Comment by willkara** [comment]
Awesome!

 

Thank you!

 

Should I use the lib locally or will there be a NuGet release soon?

 

*	Will

**Comment by decriptor** [comment]
@willkara It depends. I'm hoping to do a new release in the near future. I suppose it depends on how soon you need it. I'm going through and cleaning up some code. I'd like to do that before the release so I'm not sure how soon I can promise a release. I'm hoping in the next couple or so weeks?

Though, 2.2.0 already targeted netstandard 2.0, so that should probably work already?

**Comment by willkara** [comment]
I just tested and it should be good enough for now. I’m still in the very early stages on my project so no rush if it takes a month or so.

 

*	Will

**Comment by decriptor** [comment]
Glad to hear it! I'm curious, can you share what you project is?

**Comment by willkara** [comment]
No problem! I’m finally developing something I’ve been thinking of for a while. The idea is that it’s a web-app to help manage your multimedia collections. I know it’s been done before, but it should be a fun thing to put together.

 

*	Videos (Movie/TV, Home Movies)
*	Audio (Music)
*	Images

 

You’d be able to do mass renaming, fix titles, query IMDB/TVDB for info and embed in the files …etc.

 

So I’d need TagLib to help tweak titles/info and maybe eventually integrate ffmpeg for some conversion 😊
