### ISSUE TITLE
Opus file corrupted by release 2.2.0 of TagLibSharp

### ISSUE THREAD

**Issue by Ja-mi** [mono/taglib-sharp#221]
With TagLibSharp release 2.2.0, I am trying to add XiphComment to opus files which seem to corrupt files.

opusinfo return this error :
**Negative or zero granulepos (0) on Opus stream outside of headers. This file was created by a buggy encoder**

An error is also returned by foobar2000 v1.4 when verifying integrity of the tagged opus file :
**Nonsense Ogg granulepos value, file is not properly seekable.**

## Steps to reproduce, with Powershell on Win10 :
1. First I generate proper opus files and check their validity with `opusinfo` :
    ```
    opusenc --quiet speech_orig.wav speech.opus
    copy speech.opus speech_tagged.opus
    opusinfo -q speech.opus
    ```

2. Then I tag the copied file :
    ```
    Import-Module 'C:\Program Files\PackageManagement\NuGet\Packages\TagLibSharp.2.2.0\lib\net45\TagLibSharp.dll'

    $audiofileinfo = [TagLib.File]::Create('C:\Temp\speech_tagged.opus')

    $audiofileinfo.Save()
    ```

3. Finally I check the tagged file which results in the following error :
    ```
    PS C:\temp> opusinfo -q speech_tagged.opus
    Processing file "speech_tagged.opus"...

    Negative or zero granulepos (0) on Opus stream outside of headers. This file was created by a buggy encoder
    ```

### Notes
* TagLibSharp.dll is the 2.2.0 release from NuGet.org
* opusenc and opusinfo are from opus-tools 0.2 (Opus 1.3) : https://opus-codec.org/downloads/
* "speech_orig.wav" is the uncompressed "Opus speech samples, various bitrates" sample from https://opus-codec.org/examples/

**Comment by decriptor** [comment]
@Ja-mi I just merged the fix from @ta264. Would you be able to pull the source and test?

**Comment by Ja-mi** [comment]
@decriptor : I have not any build environment to generate the library.
Can you provide me a binary net45\TagLibSharp.dll ?
I would be glad to test.

**Comment by decriptor** [comment]
@Ja-mi Sure, Let me see if I can build and share a dll with you. Are you targeting `net45` or something newer like .net core? or .net standard?

**Comment by Ja-mi** [comment]
@decriptor : net45

**Comment by decriptor** [comment]
@Ja-mi  Sorry, this is net462 and netstandard 2.0. I hope that this'll still work for you.
[TagLibSharpBuilds.zip](https://github.com/mono/taglib-sharp/files/5303200/TagLibSharpBuilds.zip)

**Comment by Ja-mi** [comment]
Thanks, net462 is fine.

I have just redone the exact same test I had described in "Steps to reproduce, with Powershell on Win10" when I had opened this issue.

And the result is OK : the tagged opus file is valid when I check it with opusinfo and foobar2000 v1.4.

I will do further experiment.

**Comment by decriptor** [comment]
@Ja-mi fantastic, thanks for testing. I'm going to mark this as closed, but if you hit anything feel free to re-open or file a new issue.
