### ISSUE TITLE
JPG detection bug

### ISSUE THREAD

**Issue by EatonZ** [mono/taglib-sharp#238]
[GetExtensionFromData](https://github.com/mono/taglib-sharp/blob/333bdcbaec7c800ff66bd6d9839f3706ef262ebd/src/TaglibSharp/Picture.cs#L548) has a bug where it can fail to detect certain types of JPG images.
The detection works by checking the first 4 bytes, which are: 0xFF, 0xD8, **0xFF**, **0xE0**.

The bolded bytes are where the problem is. According to 010 Editor, this is the "marker" value. taglib appears to only check for M_APP0 (0xFFE0). Some JPGs, such as ones exported from Photoshop, can use a different marker value, such as M_DQT (0xFFDB).
Thus, when initializing a `Picture` class on an array of bytes, the JPG will not be detected if the marker is anything other than M_APP0.

**Comment by Starwer** [comment]
`GetExtensionFromData` is indeed far from being exhaustive and bullet-proof. It is a fallback method to attempt to retrieve type of a raw data we attach to a tag (typically a picture, but not always even!) without knowing its file-extension or mime-type. The way data types are inferred looking at the first bytes is quite empirical I think... If you can improve it or extend the filetypes which can be detected, it you'll be more than welcome !

**Comment by EatonZ** [comment]
@Starwer I think a better way would be to check the first 2 bytes of the JPG (SOIMarker) and the last 2 bytes (EOIMarker).
Those _should_ be in every valid JPG. I'll look into getting a PR up for it.
