### ISSUE TITLE
why id3 tags are always created at read of Mpeg audiofiles?

### ISSUE THREAD

**Issue by Vasilich** [mono/taglib-sharp#251]
Thanks for great TagLib# library.

I am using TagLib# to analyze mp3 files, and had recently some files with several tags of same type (e.g. id3v2) in one file. So far i found the way to detect/list all those tags with using `(tagFile.Tag as TagLib.NonContainer.Tag).Tags`.
I read tags with `tagFile = TagLib.File.Create(filename);` and it correctly reports, that e.g. tagFile.TagTypesOnDisk are _Id3v1_ and _Ape_. But  `(tagFile.Tag as TagLib.NonContainer.Tag).Tags`  in that case has 3 elements - **_id3v2_**, _Ape_ and _Id3v1_.
This is because in /src/TaglibSharp/Mpeg/AudioFile.cs there is an implementation of ReadEnd method, where id3v1 and id3v2 tags are **always** created, even those don't exist in file:
```C#
		protected override void ReadEnd (long end, ReadStyle propertiesStyle)
		{
			// Make sure we have ID3v1 and ID3v2 tags.
			GetTag (TagTypes.Id3v1, true);
			GetTag (TagTypes.Id3v2, true);
		}
```
What was the intention of doing this? For what is it good?
After setting second parameter of call GetTag to _false_ i get everything as it is in file. 
But there should be a reason for forced creating of both id3v1 and id3v2 tags on reading (as current TagLib# code does)? 
Please comment.

**Comment by hwahrmann** [comment]
I went back in file history as far as i could get and this was already in the code at 2007.

I guess they wanted to make sure that in any case a ID3v2 is there.
i think the only way to work around for you is to check if TagTypesOnDisk does not contain id3v2 and if this is the case you would remove it before saving the file.

i fear that a lot of programs are relying on the fact that when opening a mp3 a id3v2 is always created.
changing it in the code, would cause them to fail.

**Comment by Vasilich** [comment]
Not only id3v2 - this flag is true also for id3v1.
Maybe we can create flag/property for it, and set its default value to "true" as it is now, but with possibility to change it before reading tags from disk?

Anyway - thanks for looking into it.

Right now i have corrected it in local code after checking out TagLib# and taking only that part what i need for my app (tags in MP3 file).

**Comment by hwahrmann** [comment]
Right. But as i said, there are a lot of applications using taglibsharp, which are relying since > 14 years on the fact that those tags are there.
So only a flag could be the option to prevent that.
i'll see, if i can do something

**Comment by decriptor** [comment]
Assuming #254 fixes this I'm going to close this issue. If not, please reopen
