### ISSUE TITLE
Reading/Writing Chapters

### ISSUE THREAD

**Issue by VarSell** [mono/taglib-sharp#285]
Hi,
May I ask if reading / writing chapters to anf from a file is supported? I've tried searching up, but could not find anything relating to that in TagLib

**Comment by Starwer** [comment]
Hi @VarSell, 
there is no such a ready-to-use facility in TagLib#. You can access low-level tag definitions and then read/write chapters infos into that, but you'll have to understand what the format of this is, and do that (differently) for each format you want to support.

**Comment by VarSell** [comment]
Okay, thanks for the explanation:)
