### ISSUE TITLE
MKV files without a pre-existing Episode/Track tag section do not store Track/Title properly

### ISSUE THREAD

**Issue by GRMorgan** [mono/taglib-sharp#289]
Episodic video tag structure in MKV is:

1. Collection (70)
    1. TITLE (maps to Album)
2. Volume (60)
    1. PART_NUMBER (maps to Disc)
3. Episode (50)
    1. TITLE (maps to Title)
    3. PART_NUMBER (maps to Track)

Track music tag structure is:

1. Collection (70)
2. Album (50)
    1. TITLE (maps to Album title)
3. Part (40)
    1. PART_NUMBER (maps to Disc)
4. Track (30)
    1. TITLE (maps to Title)
    1. PART_NUMBER (maps to Track)

See: https://www.matroska.org/technical/tagging.html

The problem in the current MKV tagging solution is Title and Track map to the lowest numbered tag section in the MKV file when they should map to Episode for video and Track for audio.

https://github.com/mono/taglib-sharp/blob/6a746346e80abdfc30d23237ebd2c360be1cb7fb/src/TaglibSharp/Matroska/Tag.cs#L524

https://github.com/mono/taglib-sharp/blob/6a746346e80abdfc30d23237ebd2c360be1cb7fb/src/TaglibSharp/Matroska/Tag.cs#L906

This is superficially fine when dealing with a file that already has at least the basic elements of the correct structure in place (though if it has additional sub tags like Scene or Shot it will incorrectly map to those). When a file does not have the correct structure the Title tag ends up with the exact same value as the Album tag and the Disc tag ends up with the exact same value as the Track tag. This leads to the situation where the following code fails to save the tags properly

```csharp
var tfile = TagLib.File.Create(filePath);
tfile.Tag.Album = showTitle;
tfile.Tag.Title = episodeName;
tfile.Tag.Disc = seasonNo;
tfile.Tag.Track = episodeNo;
tfile.Save();
```

After running code like this and then reloading the file the Album will be set to episodeName and the Disc will be set to episodeNo on MKV files that are missing (entirely or partially) existing tag meta data or if you've cleared the MKV tags manually during the program.

The solution to this is to use the section specific look up that the Album and Disc properties use in order to ensure Title and Track are saved to tag structures

```csharp
		public override uint Track{
			get {
				var tag = TagsGet (false, IsVideo ? TargetType.Episode: TargetType.Track);
				return tag?.GetUint ("PART_NUMBER") ?? 0;
			}
			set {
				var tag = TagsGet (false, IsVideo ? TargetType.Episode: TargetType.Track);
				if (tag != null) tag.Set ("PART_NUMBER", null, value);
			}
		}

		public override string Title {
			get {
				var tag = TagsGet (false, IsVideo ? TargetType.Episode: TargetType.Track);
				return tag?.GetString("TITLE");
			}
			set {
				var tag = TagsGet (false, IsVideo ? TargetType.Episode: TargetType.Track);
				if (tag != null) tag.Set ("TITLE", null, value);
			}
		}
```

This will ensure the tags never elide and also ensures that track/episode data will not accidentally end up on a sub track/episode tag.

**Comment by GRMorgan** [comment]
I don't actually mind putting together a PR to fix this myself. I just thought I'd check with you guys that you are happy that what I've said above is correct before I go away and do a bunch of work that might end up touching on an issue that is already known about and preferred.

**Comment by Starwer** [comment]
Hi @GRMorgan,

Unfortunatly, I couldn't reproduce the problem.
At least that's a good test-idea. I've developped a test to reproduce the problem you reported.
Here is the snippet, with tmp_file being an mkv file:
```C#
	// Remove tags
	var tmp = File.Create (tmp_file);
	tmp.RemoveTags (TagTypes.AllTags);
	tmp.Save ();

	// Write tags
	tmp = File.Create (tmp_file);
	tmp.Tag.Album = "Album tag 123";
	tmp.Tag.Title = "Title tag 456";
	tmp.Tag.Disc = 18;
	tmp.Tag.Track = 23;
	tmp.Save ();

	// Check tags
	tmp = File.Create (tmp_file);
	var tag = tmp.Tag;
	Assert.AreEqual ("Album tag 123", tag.Album);
	Assert.AreEqual ("Title tag 456", tag.Title);
	Assert.AreEqual (18, tag.Disc);
	Assert.AreEqual (23, tag.Track);
```

The intermediate file saved shows that no Matroska `Tags` remain after the first `tmp.Save()`.
After the second `tmp.Save()`, here is what I could observe on the mkv file:

![image](https://user-images.githubusercontent.com/8810885/162064509-60b4ac8d-8bb4-4cbe-89f7-e934e5648d11.png)

This looks just perfect.

Also, I disagree with the proposed solution...


Would you please share the mkv file which presents the problem, so that I could maybe faithfully reproduce it ?

Thanks forward !

**Comment by GRMorgan** [comment]
Interesting. I'll see if I can get hold of the original file that caused this issue tomorrow. I've since manually forced it to do what I expect by casting and forcing the right tags in so I'll need to find a backup.

I suspect this is not failing because clear does not actually clear. It preserves the tag represented by the property Medium and puts it back in the collection.

```csharp
		protected override void ClearItems ()
		{
			Title = null;
			var medium = Medium;

			foreach (var tag in this) {
				tag.Clear ();
			}

			base.ClearItems ();

			// Keep Medium Tag reference unchanged (if any)
			if (medium != null) Add (medium);
		}
```

Medium in turn returns the lowest tag level that isn't 40 that has no elements

```csharp
		public Tag Medium {
			get {
				Tag ret = null;
				bool vid = IsVideo;

				// Try to find a default TargetType
				for (int i = Count - 1; i >= 0; i--) {
					ret = this[i];
					if (ret.TargetType == TargetType.DEFAULT) // Avoid CD/DVD
					{
						if (ret.Elements == null) return ret;
					}
				}

				// Lower level without UID is the Tag representing the file
				// List is sorted in descending TargetTypeValue
				for (int i = Count - 1; i >= 0; i--) {
					ret = this[i];
					if (ret.TargetTypeValue != 40 || !vid) // Avoid CD/DVD
					{
						if (ret.Elements == null) break;
					}
				}


				return ret;
			}
		}
```

Based upon this logic I'd expect a cleared MKV file to still contain a Track/Episode tag. It might be worth casting tmp.Tag to TagLib.Matroska.Tag and looking at tmp.Tag.Tags[0] to see what the TargetType on it is.

I'll see if I can find the file that originally brought this issue to my attention regardless. If the above logic is correct it shouldn't be impossible to artificially create one via some debugger bashing.

**Comment by GRMorgan** [comment]
I've managed to create a file with this problem. As expected it comes when a file only has the 70 level tag. I confirmed that if you clear a normal file it leaves the DEFAULT or lowest level tag with null Elements so any working file you try and manufacture this problem on will naturally fail.

I additionally found issues if there was a file that had level 50 and lower tags but all of them contained elements. The relevant properties all exclude any tag which doesn't have null for Elements so that is effective as if that file didn't have that tag.

When I run the code below

```csharp
        // Write tags
        var tmp = TagLib.File.Create(tmp_file);
        tmp.Tag.Album = "Album tag 123";
        tmp.Tag.Title = "Title tag 456";
        tmp.Tag.Disc = 18;
        tmp.Tag.Track = 23;
        tmp.Save();

        // Check tags
        tmp = TagLib.File.Create(tmp_file);
        var tag = tmp.Tag;
        Console.WriteLine("Album tag 123: " + tag.Album);
        Console.WriteLine("Title tag 456: " + tag.Title);
        Console.WriteLine("18: " + tag.Disc);
        Console.WriteLine("23: " + tag.Track);
```

I get the output

```
Album tag 123: Album tag 123
Title tag 456: Title tag 456
18: 23
23: 23
```

I additionally created a file which had a 70 and a 60. When you run with that you get Disc/Track unifying but not Album/Title

```
Album tag 123: Album tag 123
Title tag 456: Title tag 456
18: 23
23: 23
```

[sample_640x360_70_only.zip](https://github.com/mono/taglib-sharp/files/8441180/sample_640x360_70_only.zip)
[sample_640x360_70_60_only.zip](https://github.com/mono/taglib-sharp/files/8441205/sample_640x360_70_60_only.zip)

**Comment by Starwer** [comment]
> I suspect this is not failing because clear does not actually clear. It preserves the tag represented by the property Medium and puts it back in the collection.

Beware that in Matroska, `Tags` and `Tag` are two different things. `Tags` is unique EBML element and contains all the `Tag` EBML elements, each `Tag` representing a target level (70, 60, 50...). The `ClearItems ()` method you showed will effectively clear every `Tag` content, then it will remove every `Tag` references it lists, keeping only the medium one which has been cleared in the foreach loop like other `Tag`. When saving the file, the empty `Tag` and `Tags` will not be written at all to file.

**Comment by GRMorgan** [comment]
> > I suspect this is not failing because clear does not actually clear. It preserves the tag represented by the property Medium and puts it back in the collection.
> 
> Beware that in Matroska, `Tags` and `Tag` are two different things. `Tags` is unique EBML element and contains all the `Tag` EBML elements, each `Tag` representing a target level (70, 60, 50...). The `ClearItems ()` method you showed will effectively clear every `Tag` content, then it will remove every `Tag` references it lists, keeping only the medium one which has been cleared in the foreach loop like other `Tag`. When saving the file, the empty `Tag` and `Tags` will not be written at all to file.

Yeah I got to the bottom of what was going on earlier. The point is more explaining why you're struggle to create a file with the issue, it defaults to leaving a tag level 50 in the file and if that exists then the bug doesn't appear . The specifics of how the tag library functions means that it basically cannot break an MKV file so that the tagging bug appears. I had to do some interesting things with tags to make it break..

Anyway files that have the issue are attached above.

**Comment by GRMorgan** [comment]
Interestingly if I run the test twice on the 70 level file (i.e. run it on the output of the first test) the level 60 item suddenly appears and the title/album issue (but not the disc/track issue) goes away.

**Comment by Starwer** [comment]
> As expected it comes when a file only has the 70 level tag. 

Ok, in that case I can make sense of what happens. In case you only have one `Tag` without any `Chapter UID`, TagLib# will assume that this tag represents the medium (video, file) entirely. This might sound silly, but that something which is perfectly forseen in Matroska: see the "One file with all DVDs" case in this [Official Matroska page](https://www.matroska.org/technical/tagging-video-example.html)

As a result, in this example, this means the file represents a full collection. The `TagLib.Tag.Title` property always represents the title of the file (medium) as well, so it consistently maps the title to the collection tag. I think this is a sound behavior, not a bug.

If you didn't expect the file to represent a full collection, the real problem comes from the fact that this file was improperly tagged at first, confusing what TagLib# could infer from it (dirt-in-dirt-out). This video should have contained another `Tag` bellow the collection `Tag` to represent the medium (a `Tag` without UID or with empty `Targets`). Matroska is a powerful container, and the absence of an element has a strong meaning. So it's also easy to mess it up, and it's better to start with no tag at all than having a partial sloppy tagging done on it already.

Back to yours: if you're sure that you will never encounter a video-file containg a full collection or season, you'd better remove the tags (using `RemoveTags ()`) to fix any potential bad tagging the file may contain, prior to retagging it.

**Comment by GRMorgan** [comment]
If you're happy this is working as intended I'm happy to close this. It isn't hard for me to do a quick query to fix the tags, it just seemed odd behaviour. If anyone else runs into this issue the code I'm running to fix the tags is

```csharp
        private static void FixTags(TagLib.File file)
        {
            if(file.Tag is TagLib.Matroska.Tag mkvTag)
            {
                if(!mkvTag.Tags.Where(tag => tag.TargetTypeValue == (ushort) TagLib.Matroska.TargetType.COLLECTION)
                               .Where(tag => tag.Elements == null)
                               .Any())
                {
                    _ = new TagLib.Matroska.Tag(mkvTag.Tags, TagLib.Matroska.TargetType.COLLECTION);
                }

                if (!mkvTag.Tags.Where(tag => tag.TargetTypeValue == (ushort)TagLib.Matroska.TargetType.VOLUME)
                                .Where(tag => tag.Elements == null)
                                .Any())
                {
                    _ = new TagLib.Matroska.Tag(mkvTag.Tags, TagLib.Matroska.TargetType.VOLUME);
                }

                if (!mkvTag.Tags.Where(tag => tag.TargetTypeValue == (ushort)TagLib.Matroska.TargetType.ALBUM)
                                .Where(tag => tag.Elements == null)
                                .Any())
                {
                    _ = new TagLib.Matroska.Tag(mkvTag.Tags, TagLib.Matroska.TargetType.EPISODE);
                }
            }
        }
```

The discards are fine here as the constructor adds the tag to the Tags collection anyway. I have no idea if this behaviour is an officially supported use case either.

This is working on the assumption I'm going to immediately overwrite all the tag data with stuff pulled down from an API so it is worth noting **this does not preserve the value of existing tags**. If you want that behaviour you'll need to capture the data at the start of FixTags and restore it at the end.
