### ISSUE TITLE
NuGet Update?

### ISSUE THREAD

**Issue by jamsoft** [mono/taglib-sharp#291]
Hi All,

Are there any plans to publish a 2.3? The nuget is now nearly 3 years old.

**Comment by igor-rif-shevchenko** [comment]
@decriptor @akoeplinger  can anyone do the update? I was asking about it for couple months...

**Comment by jamsoft** [comment]
Bump. Anyone?

**Comment by decriptor** [comment]
My apologies. I'll follow up on this this evening after work.

**Comment by jamsoft** [comment]
No problem peeps. Thanks. Just would be good to get all the work rolled up and packaged.

**Comment by decriptor** [comment]
@igor-rif-shevchenko my apologies. Just trying to get through some deadlines at work first. I should have some time next week. If you could ping me on Tuesday next week to remind me that'd be great.

**Comment by igor-rif-shevchenko** [comment]
Will do, thank you!

**Comment by igor-rif-shevchenko** [comment]
@decriptor it's Tuesday)

**Comment by igor-rif-shevchenko** [comment]
@decriptor perhaps someone else can back you up while you're busy?

**Comment by decriptor** [comment]
@igor-rif-shevchenko sorry, I think I finally unburied myself a bit. I should have this knocked out by this weekend. I'll update this as soon as it goes live.

**Comment by igor-rif-shevchenko** [comment]
![just-waiting-for-dfbe76cfed](https://user-images.githubusercontent.com/16201350/181345409-106066c8-e406-4a99-a5d7-ff9967d3d3a2.jpg)

**Comment by jamsoft** [comment]
Even the Wookie has died!!!!!!!!!!!!!!!!!!!!

**Comment by igor-rif-shevchenko** [comment]
A little humor while we wait)
![1858e0fbc8bbc26d6990fe6467915669--jim-carey-daily-inspiration](https://user-images.githubusercontent.com/16201350/181789195-d4a0d5bd-925b-44b5-92d5-7281ddc10e2b.jpg)

**Comment by decriptor** [comment]
ok, that is hilarious, and I absolutely loved the humor!!!!

So, without further delay, I finally published a new release :)

https://github.com/mono/taglib-sharp/releases/tag/TaglibSharp-2.3.0.0
https://www.nuget.org/packages/TagLibSharp/2.3.0

**Comment by jamsoft** [comment]
Nice work dude. Will get on and check it asap.
