### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by castilma** [mono/taglib-sharp#40]
Hey guys,
since 2012 there hasn't been any new release and I wonder why. Don't you feel that there have been enough changes since then?

I'm asking, because the changes since 2.1 have not been imported in the Ubuntu package. And if I had to guess, I'd say it's because there is no newer release here in the upstream.
(I asked at launchpad: https://answers.launchpad.net/ubuntu/+source/taglib-sharp/+question/402667 )

I'd really like to have opus tag support without compiling things myself.
Martin

**Comment by twon33** [comment]
Yes, please. I grabbed the most recent package from NuGet and promptly got burned by [an XmlException issue](https://github.com/mono/taglib-sharp/commit/98cc8772e870c5c254c81bb4b1f33bc92dfc3c3b) that was fixed in August 2012.

**Comment by decriptor** [comment]
@castilma I'm sure there are plenty of changes. An update hasn't been made partly because no one has really been maintaining this repository. I'll see what I can do and try to create a release by the end of the week.

**Comment by castilma** [comment]
Thank you very much!

**Comment by decriptor** [comment]
@castilma I took a quick glance at the existing PRs. I'm going to see if I can clear some of them out and then try to get a release going. I figure we may as well get as many fixes is as we can ;)

**Comment by alanmcgovern** [comment]
We should add a makefile target to build the nupkg to make it easier to ship new builds. Then we can contact kzu to get the nuget updated. He seems to own that package.

**Comment by castilma** [comment]
So, how is it going?

**Comment by decriptor** [comment]
Sorry, I completely dropped the ball on this. I'll try and make it a higher priority.

**Comment by lesderid** [comment]
So err, any progress?

**Comment by castilma** [comment]
I just hope the release doesn't come after hl3.

**Comment by decriptor** [comment]
I'm so sorry. I'll try and find some time to figure this out and pull together a release :)

**Comment by decriptor** [comment]
Ok, I finally got the travis-ci build going again. I'll look at getting a release going next.

**Comment by DasBiest** [comment]
any news?

**Comment by Starwer** [comment]
@decriptor: Is Travis taking care of the release as well ? Especially release as a Nuget package ?

**Comment by mskurnik** [comment]
I agree that a new release would be nice especially now that this supports Net Standard as I no longer have to use a fork of this.

**Comment by anthonylavado** [comment]
Hi @decriptor!
We are using TagLib# over at Jellyfin, and would really love it if there was a new release to NuGet. Is there any way we can help?

**Comment by decriptor** [comment]
@anthonylavado I really want to get https://github.com/mono/taglib-sharp/pull/117 merged first. Once that is merged I think I'm good to create a new release. It'll include multi-targeting for net462 and .net standard 2.0. I think the current problem is that the Makefile stuff is busted. I'm working on it this morning. I'm tempted to just dump all of the autotools stuff though. This is just a simple library that essentially produces a single dll.

**Comment by decriptor** [comment]
Closing this issue in favor of #138 which is the issue to track the 2.2.0.0 release.
