### ISSUE TITLE
Taglib sharp in Xamarin

### ISSUE THREAD

**Issue by lokinfey** [mono/taglib-sharp#46]
<img width="1280" alt="screen shot 2016-12-15 at 3 08 48 pm" src="https://cloud.githubusercontent.com/assets/4607663/21214914/b097adfe-c2d8-11e6-93bf-84c9328ff444.png">

this is a problem . I want to read flac in Xamarin.iOS but give this error

**Comment by decriptor** [comment]
This is probably much later than you'd like, but I've updated the code base to multitarget now. The new release will support netstandard 2.0 now. This should work just fine with Xamarin. I'll close this issue, but if it isn't working with the new release please re-open.
