### ISSUE TITLE
Cannot get correct AAC ADTS bitrate

### ISSUE THREAD

**Issue by PeoLeser** [mono/taglib-sharp#51]
The encoder is `qaac 2.55, CoreAudioToolbox 7.10.6.0, AAC-LC Encoder, TVBR q127, Quality 96`

**Comment by PeoLeser** [comment]
The correct bitrate should be computed by `sizeof("mdat") * 8 / Duration` instead of read from the header.

**Comment by decriptor** [comment]
@PeoLeser any chance I could talk you into writing a unit test for this and documenting the unit test? Or even better the unit test and a fix? :)

**Comment by PeoLeser** [comment]
@decriptor I have uploaded the unit test.Thanks for your attention.
[AAC_Test.zip](https://github.com/mono/taglib-sharp/files/752719/AAC_Test.zip)

**Comment by PeoLeser** [comment]
Due to the definition in the latest ISO specification, the "avgBitrate" box should be zero if using VBR. Close.

**Comment by shaforostoff** [comment]
this code makes a rough guess about file's bitrate and length:

https://github.com/taglib/taglib/pull/856
