### ISSUE TITLE
Porting to .NET Core.

### ISSUE THREAD

**Issue by willkara** [mono/taglib-sharp#60]
I was wondering if there's any plans on porting to the .NET Core spec.

We would probably want to create a new project possibly under Mono or another account. What is everyone's thoughts on this?

I've already started looking at it and it looks like porting it wouldn't be a problem.

[ApiPortAnalysis.xlsx](https://github.com/mono/taglib-sharp/files/893961/ApiPortAnalysis.xlsx)

**Comment by PeterHagen** [comment]
I didn’t test everything, but I took the source and added it to a .Net Core project. It worked out of the box as far as I can tell

**Comment by willkara** [comment]
@PeterHagen , if you have a branch and push it up. I could help you test it/look at everything.

**Comment by decriptor** [comment]
If possible I think it'd be great to make this a .net standard library.

**Comment by PeterHagen** [comment]
I made a few more changes to get it working, then I remembered, but I’ll see if I can make a commit out of it, by merging my changes with the latest commit. Will try this weekend.

**Comment by willkara** [comment]
@PeterHagen , awesome! Looking forward to testing it out.

**Comment by calumfasetto** [comment]
Have there been any updates to this? A branch that can be pushed perhaps?

**Comment by PeterHagen** [comment]
Just let me know how :)

**Comment by decriptor** [comment]
Now that .net standard 2.0 has been released I'd like to take a serious look at porting this to `2.0`.

**Comment by PeterHagen** [comment]
Good plan. I did a quick test after installing the new VS 2017 15.3, and created a new project and solution with .net standard 2.0. The code builds without any messages. I then tried to upgrade the test project. NUnit is supported, but I get a message about the Gdk namespace, on the ImageTest class. So, I need the gdk-sharp and glib-sharp project, but not sure where to get it

So, converting it is easy! Testing it might be a bit harder

**Comment by decriptor** [comment]
mmm, that'll be interesting. I'll have to look into that. Those come from gtk-sharp and likely the gtk-sharp 2.12 branch -> github.com/mono/gtk-sharp

**Comment by decriptor** [comment]
Thinking about it though, we don't necessarily need the test projects to be .net standard 2.0 anyways... at least I don't think we would?

**Comment by PeterHagen** [comment]
The cool part about .net standard 2 (or .net core 2), that now I can reference the current package from nuget, without it being .net standard. So, for me it means I don’t have to build it from source anymore. But it would be create if the nuget package will be updated with the latest version, and preferable to .netstandard2.

About the tests, you could presume that if the test run positive on .net 4.5, they would also be positive on .net standard. But then again, there might be compatibility issues.

**Comment by PeterHagen** [comment]
I made a fork of the repository and updated it solution and project file. If you want to try it, here is the url: https://github.com/PeterHagen/taglib-sharp <https://github.com/PeterHagen/taglib-sharp>

**Comment by jamsoft** [comment]
This definitely gets my vote!

**Comment by FasettoAndrew** [comment]
Could the forked repo be added to NuGet as a seperate package? When I try and install the existing TagLib# NuGet package into a blank .net standard class library project I get and error and it rolls back the installation.

**Comment by FasettoAndrew** [comment]
I have build and push the fork made by @PeterHagen to NuGet.org. You can view here:
https://www.nuget.org/packages/taglib-sharp-netstandard2.0/2.1.0

Hopefully this is ok. Let me known if there is any problems with this or the NuGet package.

**Comment by elfalem** [comment]
Thanks @PeterHagen  and @FasettoAndrew. I was able to reference and use the NuGet package from a .net core 2 project on Linux using VS Code.

**Comment by decriptor** [comment]
I'd love to know how that works out and if there are any issues. I'd love to just move this project over to .NET Standard 2.0. Anything before 2.0 seemed to be problematic due to the available API surface.

**Comment by Lutando** [comment]
Any news on this yet?

**Comment by Starwer** [comment]
Sorry, this didn't work for me. 
I've tried to include the nugget package on Windows 7, Visual Studio 2015, .NET 4.6.1.
I guess I have to install Visual Studio 2017 ? If so, I'll give it a second try.

**Comment by Starwer** [comment]
I've tried again with Visual Studio 2017 and .NET 4.6.1. It worked, but not together with https://github.com/dwmkerr/sharpshell, which is a "must have" requirement for my project. I guess sharpshell  is just not compatible with .NET Core.

**Comment by decriptor** [comment]
.net standard 2.0 support has been merged into master now.

**Comment by FasettoAndrew** [comment]
Has the official NuGet package been updated with this change?

**Comment by TMily** [comment]
No ~~~

**Comment by scavarda** [comment]
Is there an official taglib 2.1.0.0 based on netstandard 2.0 now?
Or shall we use an outdated version from https://github.com/PeterHagen/taglib-sharp ?

**Comment by sepehr1014** [comment]
Any updates on this?

**Comment by decriptor** [comment]
@sepehr1014 I've been working on a new branch to improve the layout and bring in .net standard. It is getting close... I hope.

https://github.com/mono/taglib-sharp/tree/build_tweaks

If someone is a autotools expert I'd love the help with that. I *think* it is pretty close?

**Comment by OronDF343** [comment]
@FasettoAndrew your NuGet package is missing the xml-doc comments

**Comment by decriptor** [comment]
@JoshSchreuder The one PR I'd like to land before doing a release would be this one: https://github.com/mono/taglib-sharp/pull/117
Unfortunately I messed up the autotools stuff and want to get that fixed first. I suppose I need to rebase it first :)

**Comment by JoshSchreuder** [comment]
@decriptor no worries, let me know if I can help with anything :)

**Comment by decriptor** [comment]
I finally merged PR#117. We now officially multitarget both net462 and netstandard2.0. I'm going to start working on a new release soon. I'll update issue#40
