### ISSUE TITLE
Pictures in MKV

### ISSUE THREAD

**Issue by Starwer** [mono/taglib-sharp#65]
Apparently, setting/getting a Tag.Pictures field on a MKV file is not possible. 

Would it be possible to add support to Pictures in MKV (in Matroska world: Attachments) ?
If not, shall I do it myself (will it then be integrated to this project) ?

**Comment by decriptor** [comment]
If you want to submit a PR with the support and unit tests I'd be happy to include it in this project.

**Comment by Starwer** [comment]
I didn't know where this project would lead me to.
Finally, I did slightly more than ading basic picture support, and developped a full support for Matroska in TagLib# (and support of VS 2015 Windows). I believe this is a big plus for this Library, and that it will revive some activity on this great project. 
Looking forward to hear your comments, and hope you can integrate it.

**Comment by decriptor** [comment]
Can you reference this issue in the PR?

**Comment by decriptor** [comment]
@Starwer Can this be closed now?

**Comment by Starwer** [comment]
Integrated in PR #68. Pictures are fully supported in MKV now.
