### ISSUE TITLE
Is TagLib-Sharp dead ?

### ISSUE THREAD

**Issue by Starwer** [mono/taglib-sharp#66]
Looking at #40, it seems like the owner (Decriptor?) has no time anymore to spend on TagLib-sharp. 

I'm really ready to contribute. This project is great, and my own project would really benefit from this Library. But its support to videos format is too limited for my use. If I could extend it, it would benefit to the community, not only my own project.
But before I start, I want to make sure I'm not redirecting my free time into > /dev/null

Is there anyone still owning/supporting this project ?

**Comment by decriptor** [comment]
@Starwer I'm not sure I really "own" this project, but I pay some limited attention to it. It is also used in one of my projects. I've somewhat adopted the policy that if you include unit tests with the PR an they pass I'll more than likely merged the PR.

**Comment by Starwer** [comment]
Thanks for your reply, and I'm glad to read that :)
Sounds like a fair deal. I'll then create a PR (I guess it stands for Pull Request) about improving the Matroska video fomat (to be realy write-able, and to support Attachments). 
There is  only one problem: I work on Windows, and the Nunit tests do not seem to work there. Plus: there is no test yet for Mkv files. I'll try to find my way there...

**Comment by tcHylmrX** [comment]
I still use the library too.

**Comment by Starwer** [comment]
Looking at the activity on PR #68, I'm happy to see that TagLib# is **not** dead.
Still, no release in 5 years is not a good sign. Seems to me like we miss a group of trusted people to support the project and take the responsibility to integrate/release the change. 
Don't get me wrong, I understand and like this organic structure where all people can willingly contribute to the project. Still I think we would all benefit in having a couple of heads setting the global direction. Also, making sure the change get integrated will re-motivate people to develop/support more.
I'm a newcomer in this project, so I don't mean to give lessons or impose my rules. I'd just like to understand what's the working structure here.
So who has a view on who is doing what in this project ?

**Comment by Starwer** [comment]
As seen how the PR #68  was handled, I happy to conclude that TagLib# is not dead :)
So this issue can be closed.
