### ISSUE TITLE
How to access the tag "Tags" on mp4 files?

### ISSUE THREAD

**Issue by rodolforubens** [mono/taglib-sharp#82]
I'm trying to modify the tag named "Tags" on mp4 files but no success, I was able to access and modify the tag **Title** and **Comments** but no **Tags**, **Ratings** nor **Subtitles**..
Thanks in advance.

edit: I'm dealing with **.mp4** and **.jpg** files.

**Comment by rodolforubens** [comment]
Btw, I need this so I can add a tag called "360", so I can upload photos and videos to Youtube/Facebook and they can detect that it is dealing with 360 stuff.

**Comment by rodolforubens** [comment]
Ha, I was able to inject the metadata I needed on .jpg files so facebook can detect it as being a panorama/360 file!

But I'm still stuck on .mp4 files ([for youtube](https://github.com/google/spatial-media/blob/v2.0/docs/spherical-video-rfc.md)), I need access to this guy:
**_moov/trak/uuid[ffcc8263-f855-4a93-8814-587a02521fdd]_**

I think it lives on the ilst box, but I have no idea how to get that box nor access and modify it.

Is it possible to do this?

**Comment by Clownfused** [comment]
No need for taglib-sharp to set the "Tags" property. You'll need to use this: https://www.nuget.org/packages/Microsoft.WindowsAPICodePack-Shell/ and then specifically look into this: shellFile.Properties.System.Keywords.Value -- The gotcha is that they use the term Keywords for coding and then in the details tab of a file it uses the term Tags. Apparently they are the same thing.

**Comment by rboy1** [comment]
MP4 tagging was fixed in #147
